Repository redhat-developer/rh-che, pull requests merged in 2018-10, with the labels that each got.

#937 Add native build profile to dashboard submodule
  assembly/fabric8-ide-dashboard-war/pom.xml
Labels: kind/enhancement, status/code-review

#895 Separate PR deployments
  .ci/cico_cleanup_dev_cluster.sh
  .ci/cico_do_docker_build_tag_push.sh
  .ci/cico_rhche_prcheck.sh
  config
  dev-scripts/deploy_custom_rh-che.sh
  dockerfiles/pr-check/Dockerfile
Labels: kind/enhancement, status/analyzing

#939 Add documentation to native dashboard build in pom.xml
  assembly/fabric8-ide-dashboard-war/pom.xml
Labels: kind/docs, status/code-review

#943 Switch of PR check deployment from user/pass to token autentication.
  .ci/cico_rhche_prcheck.sh
Labels: status/code-review

#942 Adding test for bayesian
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheSeleniumSuiteModule.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianPomXml.java
Labels: kind/enhancement, status/code-review

#923 Fix PR job link
  README.md
Labels: kind/bug, status/code-review

#960 End2end flow protection
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/com/redhat/che/wsmaster/deploy/DisableAuthenticationInterceptor.java
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/rh-che.properties
  assembly/fabric8-ide-dashboard-war/pom.xml
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
  plugins/che-plugin-analytics/che-plugin-analytics-wsmaster/src/main/java/com/redhat/che/plugin/analytics/wsmaster/AnalyticsService.java
  plugins/fabric8-end2end-flow/pom.xml
  plugins/fabric8-end2end-flow/src/main/java/com/redhat/che/end2end/End2EndFlowService.java
  plugins/fabric8-end2end-flow/src/main/java/com/redhat/che/end2end/End2EndFlowWsMasterModule.java
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/OIDCKeycloak.js
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/RhCheKeycloak.js
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/provision.html
  plugins/pom.xml
  pom.xml
Labels: status/code-review

#962 Fix PR-Check cleanup job
  .ci/cico_cleanup_dev_cluster.sh
Labels: kind/bug, status/code-review

#956 move stacks to quay
  assembly/fabric8-stacks/src/main/resources/stacks.json
  functional-tests/README.md
Labels: status/code-review

#967 Changed bash script to check for token
  .ci/cico_cleanup_dev_cluster.sh
Labels: kind/bug, status/code-review

#964 Fix pr-check build issues when building dashboard
  dockerfiles/pr-check/Dockerfile
Labels: kind/bug, status/code-review

#968 Add env vars to allow usage of exec/terminal sidecar
  openshift/rh-che.app.yaml
Labels: kind/enhancement, status/code-review

#974 Adding Che 7 Preview stacks
  assembly/fabric8-stacks/src/main/resources/stacks-images/type-che7.svg
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#977 Fix regressions and errors due to the e2e flow protection deployment
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/RhCheKeycloak.js
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/provision.html
Labels: kind/bug, status/code-review

#978 Update oso proxy url in rhche configmap
  openshift/rh-che.config.yaml
Labels: kind/task, status/code-review

#980 Also protect against global function use
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/RhCheKeycloak.js
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/provision.html
Labels: status/code-review

#981 Fix a small regression: provisioning tab not closed when finished
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/provision.html
Labels: kind/bug, status/code-review

#970 Update upstream Che version to 6.12.2
  pom.xml
Labels: kind/enhancement, status/code-review

#983 Last fixes to the end2end flow
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/provision.html
Labels: kind/bug, status/code-review

#972 Use default openshift config for client when we can't get a subject
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8OpenShiftClientFactory.java
Labels: kind/bug, status/code-review

#984 Update rh-che.app.yaml
  openshift/rh-che.app.yaml
Labels: kind/enhancement, status/code-review

#986 Change Theia broker image to one hosted in wsskeleton repo
  openshift/rh-che.app.yaml
Labels: kind/enhancement, status/code-review

#990 Set 150MB of memory limit to JWT proxy sidecar
  assembly/assembly-ide-war/pom.xml
  openshift/rh-che.app.yaml
Labels: status/code-review

#991 Add Quay imagepullsecrets to rhche ServiceAccount
  openshift/rh-che.app.yaml
Labels: kind/enhancement, status/code-review

#993 Change the title of Che7 stacks
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#995 Added command for getting OpenShift Console URL into Che 7 Stacks
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#996 Add better implementation of Theia plugin broker
  assembly/assembly-wsmaster-war/src/main/java/com/redhat/che/wsmaster/deploy/Fabric8WsMasterModule.java
  openshift/rh-che.app.yaml
Labels: kind/enhancement, status/code-review

#1010 Fixing PR check
  .ci/cico_build_deploy_test_rhche.sh
  .ci/cico_rhche_compatibility_test.sh
  .ci/cico_rhche_prcheck.sh
Labels: kind/bug, status/code-review

#965 Move to upstream 6.13.0
  assembly/fabric8-ide-dashboard-war/Dockerfile
  assembly/fabric8-ide-dashboard-war/pom.xml
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheSeleniumClassModule.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheSeleniumSuiteModule.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheTestWorkspaceProvider.java
  plugins/che-plugin-analytics/che-plugin-analytics-wsagent/pom.xml
  plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/test/java/com/redhat/che/plugin/analytics/wsagent/AnalyticsManagerTest.java
  plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/test/java/com/redhat/che/plugin/analytics/wsagent/UrlToEventFilterTest.java
  plugins/fabric8-end2end-flow/pom.xml
  plugins/fabric8-multi-tenant-manager/pom.xml
  plugins/fabric8-multi-tenant-manager/src/test/java/com/redhat/che/multitenant/Fabric8OpenShiftClientFactoryTest.java
  plugins/fabric8-multi-tenant-manager/src/test/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisionerTest.java
  pom.xml
Labels: kind/task, status/code-review

#1019 Tag functional-tests dependency image with shorthash
  .ci/cico_build_prcheck_dep.sh
Labels: kind/enhancement, status/code-review

#940 Use custom timeout in waitStatus
  functional-tests/src/main/java/com/redhat/che/selenium/core/client/RhCheTestWorkspaceServiceClient.java
Labels: kind/enhancement, status/code-review

#1022 Re: Tag functional-tests dependency image with shorthash
  .ci/cico_build_prcheck_dep.sh
Labels: kind/bug, status/code-review

#1023 Enable jwtproxy as default secure servers exposer
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/bug, status/code-review

#1021 Start workspaces like in upstream tests
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheSeleniumClassModule.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheSeleniumSuiteModule.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheTestWorkspaceInjector.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheTestWorkspaceImpl.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/WorkspaceTest.java
Labels: status/code-review

#1028 Adding 'org.eclipse.che.ls.java' to java based stacks
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#982 Run functional tests from docker image
  .ci/cico_rhche_prcheck.sh
  dev-guide.adoc
  dockerfiles/functional-tests/Dockerfile
  dockerfiles/functional-tests/docker-entrypoint.sh
  functional-tests/README.md
  functional-tests/src/test/resources/suites/simpleTestSuite.xml
Labels: kind/enhancement, status/code-review

#1018 Additional fixes for end-2-end provisioning flow and protection
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/rh-che.properties
  assembly/fabric8-ide-gwt-app/src/main/resources/org/eclipse/che/public/keycloak/OIDCKeycloak.js
  assembly/fabric8-ide-gwt-app/src/main/resources/org/eclipse/che/public/keycloak/RhCheKeycloak.js
  assembly/fabric8-ide-gwt-app/src/main/resources/org/eclipse/che/public/keycloak/provision.html
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
  plugins/fabric8-end2end-flow/pom.xml
  plugins/fabric8-end2end-flow/src/main/java/com/redhat/che/end2end/End2EndFlowService.java
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/RhCheKeycloak.js
  plugins/fabric8-end2end-flow/src/main/resources/end2end/files/provision.html
  plugins/fabric8-end2end-flow/src/test/java/com/redhat/che/end2end/End2EndFlowServiceTest.java
Labels: kind/bug, status/code-review
