Repository redhat-developer/rh-che, pull requests merged in 2018-02, with the labels that each got.

#538 [WIP] RH-CHE-532: add retrieving of service account token
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/rh-che.properties
  plugins/fabric8-multi-tenant-manager/pom.xml
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
Labels: status/code-review

#548 RH-CHE-532: fix service account token retrieval
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
Labels: kind/bug, status/code-review

#553 Update yaml files for che6
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8OpenShiftClientFactory.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
Labels: kind/enhancement, status/code-review, target/branch
