Repository redhat-developer/rh-che, pull requests merged in 2018-11, with the labels that each got.

#1044 Add sys adm env
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: kind/enhancement, status/code-review

#1048 Port recent main app yaml changes to addon's yaml
  openshift/minishift-addons/rhche/templates/rh-che.app.yaml
  openshift/minishift-addons/rhche/templates/rh-che.config.yaml
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: kind/bug, status/code-review

#1049 Create script for running functional tests.
  dockerfiles/functional-tests/docker-entrypoint.sh
  functional-tests/devscripts/prepare_env.sh
  functional-tests/devscripts/run_tests.sh
Labels: status/code-review

#1051 Adding new parameter for docker to run specific test suite.
  dockerfiles/functional-tests/docker-entrypoint.sh
  functional-tests/README.md
  functional-tests/pom.xml
Labels: kind/enhancement, status/code-review

#1050 Enabling super privileged mode for admin user
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: status/code-review

#1052 Fixing typo in env var for enabling super privileged mode
  openshift/rh-che.app.yaml
Labels: kind/bug, status/code-review

#1054 Updating rh-che to 6.13.1 upstream version
  pom.xml
Labels: status/code-review

#1046 Don't use rh-nodejs4 - rh-nodejs8 is installed.
  .ci/cico_rhche_compatibility_test.sh
Labels: status/code-review

#1057 Cosmetic change in Readme.md in order to triggering the build
  README.md
Labels: status/code-review

#1080 rh-che #1075: hot-fix to avoid NPE in ImpersonatorInterceptor when optional "Impersonate-Group" header is not set
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
Labels: kind/bug, status/code-review

#1083 rh-che #1075: Returning back passing identity_id via query parameter to oso-proxy
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
Labels: status/code-review

#1085 Fixing periodic job
  dockerfiles/functional-tests/docker-entrypoint.sh
  functional-tests/devscripts/run_tests.sh
Labels: kind/bug, status/code-review

#1089 rh-che #1075: Passing 'identity_id' to oso-proxy only via Impersonate-User Header
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
Labels: status/code-review

#1092 Updating to upstream 6.14.2 version
  pom.xml
Labels: status/code-review

#1094 Updating 'Interaction of Red Hat Che with other openshift.io services ' docs
  README.md
Labels: status/code-review

#1097 Remove usage of offline token
  dockerfiles/functional-tests/docker-entrypoint.sh
Labels: status/code-review

#1078 Fix nodejs stack run command
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/bug, status/code-review

#1101 Update wsagent debug instructions in dev-guide
  dev-guide.adoc
Labels: kind/enhancement, status/code-review

#1102 Ee test
  dockerfiles/functional-tests/docker-entrypoint.sh
  functional-tests/README.md
Labels: status/code-review

#1099 Decrease ping success threshold and add ping interval
  openshift/minishift-addons/rhche/templates/rh-che.app.yaml
  openshift/minishift-addons/rhche/templates/rh-che.config.yaml
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: kind/enhancement, status/code-review

#1103 Add e2e test suite
  functional-tests/src/test/resources/suites/e2eTestSuite.xml
Labels: kind/enhancement, status/code-review
