Repository redhat-developer/rh-che, pull requests merged in 2018-09, with the labels that each got.

#844 Updating license to EPL 2.0
  LICENSE
Labels: kind/task, status/code-review

#852 FT - workspace test
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheSeleniumClassModule.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheSeleniumSuiteModule.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheSeleniumTestHandler.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/client/RhCheTestWorkspaceServiceClient.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/CheStarterWrapper.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheTestWorkspaceImpl.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheTestWorkspaceProvider.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/WorkspaceTest.java
Labels: status/code-review

#873 Improvements to minishift addon yaml template
  openshift/minishift-addons/rhche-prerequisites/rhche-prerequisites.addon
  openshift/minishift-addons/rhche-prerequisites/templates/keycloak-template.yaml
  openshift/minishift-addons/rhche/rhche.addon
  openshift/minishift-addons/rhche/rhche.addon.remove
  openshift/minishift-addons/rhche/templates/rh-che.app.yaml
  openshift/minishift-addons/rhche/templates/rh-che.config.yaml
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: kind/enhancement, status/code-review

#847 Adding/changing server names to be in sync with upstream samples.
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#872 Add capability to share workspace by factory
  assembly/fabric8-ide-dashboard-war/src/app/workspaces/share-workspace/share-workspace.controller.ts
  assembly/fabric8-ide-dashboard-war/src/app/workspaces/share-workspace/share-workspace.html
  assembly/fabric8-ide-dashboard-war/src/app/workspaces/share-workspace/share-workspace.styl
Labels: kind/enhancement, status/code-review

#875 Changing default image for deploy script from devshift.net to quay.io
  dev-scripts/deploy_custom_rh-che.sh
Labels: status/code-review

#833 153 refactor functional tests che starter wrapper
  functional-tests/pom.xml
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheSeleniumSuiteModule.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/client/RhCheTestWorkspaceServiceClient.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/model/request/CheServerStartWorkspaceRequest.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/model/request/CheStarterCreateWorkspaceRequest.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/CheStarterWrapper.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheTestWorkspaceImpl.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheTestWorkspaceProvider.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/TestTestClass.java
Labels: kind/enhancement, status/code-review

#891 Hotfixing dockerfiles for dependency builds
  dockerfiles/functional-tests/Dockerfile
  dockerfiles/pr-check/Dockerfile
Labels: kind/bug, status/code-review

#842 Wrong noVNC port fixed.
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/bug, status/code-review

#900 Update upstream Che to 6.11.1
  plugins/che-plugin-analytics/che-plugin-analytics-wsmaster/src/main/java/com/redhat/che/plugin/analytics/wsmaster/ForwardActivityFilter.java
  pom.xml
Labels: kind/enhancement, status/code-review

#876 Adding functionality to EETest.
  .ci/cico_rhche_prcheck.sh
  functional-tests/src/main/java/com/redhat/che/selenium/core/client/RhCheTestWorkspaceServiceClient.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/ProvidedWorkspace.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/EETest.java
Labels: kind/enhancement, status/code-review

#903 Increasing memory limit to 1.5Gi for rh-che
  openshift/rh-che.app.yaml
Labels: kind/question, status/code-review

#906 rh-che #901: Adding 'MaxRAMFraction=2' and removing '-Xmx180m' from the 'che-server-java-opts'
  openshift/rh-che.config.yaml
Labels: kind/question, status/code-review

#917 Adding support of 'CHE_WORKSPACE_PLUGIN__REGISTRY__URL' required for workspace.next
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: kind/enhancement, status/code-review

#918 Fix broken workspace idling after Che rolling update
  assembly/fabric8-ide-gwt-app/src/main/resources/org/eclipse/che/public/keycloak/RhCheKeycloak.js
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8OpenShiftClientFactory.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/GuessedSubject.java
  plugins/fabric8-multi-tenant-manager/src/test/java/com/redhat/che/multitenant/Fabric8OpenShiftClientFactoryTest.java
Labels: kind/bug, status/code-review

#924 Fix typos
  dev-guide.adoc
  documentation/rh-che-prcheck/pr_check_general_squence_diagram.plantuml
Labels: kind/bug, status/code-review

#922 Fix table of contents in readme
  README.md
Labels: kind/bug, status/code-review

#928 Improve readme to give better overview of what is inside rh-che
  README.md
Labels: status/code-review
