Repository redhat-developer/rh-che, pull requests merged in 2018-04, with the labels that each got.

#618 Restore the GitHub token injection for Che 6 on OSIO
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/com/redhat/che/wsmaster/deploy/Fabric8WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakModule.java
Labels: kind/bug, status/code-review, target/branch

#619 Feature tag and push cico script
  .ci/cico_build_and_deploy_custom_rh-che.sh
  dev-scripts/deploy_custom_rh-che.sh
Labels: status/code-review, target/branch

#647 Small fixes to dev-scripts/deploy_custom_rh-che.sh
  dev-scripts/deploy_custom_rh-che.sh
Labels: kind/enhancement, status/code-review, target/branch

#651 Introduce RHEL based image
  .ci/cico_build.sh
  .ci/cico_deploy.sh
  .ci/cico_do_docker_build_tag_push.sh
  config
  dockerfiles/build.include
  dockerfiles/che-fabric8/Dockerfile
  dockerfiles/che-fabric8/Dockerfile.rhel
  dockerfiles/che-fabric8/build.sh
  dockerfiles/che-fabric8/entrypoint.patch
  dockerfiles/che-fabric8/entrypoint.sh
Labels: status/code-review, target/branch

#616 [WIP] rh-che #593: move JSON logs encoding to upstream
  assembly/assembly-main/src/assembly/base-component.xml
  assembly/assembly-main/src/assembly/conf/logback-additional-appenders.xml
  assembly/assembly-main/src/assembly/conf/tomcat-logger.xml
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: kind/bug, status/code-review, target/branch

#623 Add Sentry logger to get notification about bugs in RhChe
  assembly/assembly-ide-war/pom.xml
  assembly/assembly-main/src/assembly/base-component.xml
  assembly/assembly-main/src/assembly/conf/logback-additional-appenders.xml
  assembly/assembly-wsmaster-war/pom.xml
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
  pom.xml
Labels: kind/enhancement, status/code-review, target/branch

#660 Fix broken PVC cleaning on workspace removal
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8OpenShiftProjectFactory.java
Labels: kind/bug, status/code-review, target/branch
