Repository redhat-developer/rh-che, pull requests merged in 2018-07, with the labels that each got.

#750 openshift.io #3884: Adding query parameter back for passing identity_…
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/multicluster/MultiClusterOpenShiftProxy.java
Labels: status/code-review

#753 Updated oc tool in prcheck ci script to 3.9.0
  .ci/cico_rhche_prcheck.sh
Labels: kind/enhancement, status/code-review

#754 Adds GIT_COMMIT variable
  .ci/cico_deploy.sh
Labels: kind/enhancement, status/code-review

#760 Add properties to Telemetry events to track factory and stack usages
  plugins/che-plugin-analytics/che-plugin-analytics-wsagent/pom.xml
  plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/main/java/com/redhat/che/plugin/analytics/wsagent/AnalyticsManager.java
  plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/main/java/com/redhat/che/plugin/analytics/wsagent/EventProperties.java
  plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/test/java/com/redhat/che/plugin/analytics/wsagent/AnalyticsManagerTest.java
Labels: kind/task, status/code-review

#766 rhche #726: Changing deployment strategy from 'Recreate' to 'Rolling'
  openshift/rh-che.app.yaml
Labels: kind/bug, status/code-review

#768 Increase the `ha-proxy` timeout on the workspace agent route
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/rh-che.properties
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisioner.java
  plugins/fabric8-multi-tenant-manager/src/test/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisionerTest.java
Labels: status/code-review

#767 Removed code starting che-starter
  functional-tests/pom.xml
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/CheStarterWrapper.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheTestWorkspaceProvider.java
  functional-tests/src/test/resources/conf/selenium.properties
Labels: status/code-review

#759 rh-che #675 Increase memory limit to 3GB for workspace pods
  openshift/rh-che.config.yaml
Labels: kind/enhancement, status/code-review

#757 Update Che version to 6.8.0
  pom.xml
Labels: kind/enhancement, status/code-review

#733 Create README for functional tests.
  functional-tests/README.md
Labels: status/code-review

#769 Deploy script now can use unsecured route
  .ci/cico_rhche_prcheck.sh
  dev-scripts/deploy_custom_rh-che.sh
Labels: status/code-review
