Repository redhat-developer/rh-che, pull requests merged in 2018-05, with the labels that each got.

#662 osio #3428: Adding `-Dvertx.disableDnsResolver=true` to vert.x run / debug commands
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: status/code-review, target/branch

#664 openshift.io #3463: Adding workaround for OOM exception for building wildfly quickstart
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: status/code-review

#666 Using rhche secret for obtaining `service.account.id` / `service.account.secret`
  openshift/rh-che.app.yaml
Labels: status/code-review, target/branch

#648 Set workspace idling to 15 minutes
  openshift/minishift-addons/rhche/templates/rh-che.config.yaml
  openshift/rh-che.config.yaml
Labels: kind/task, status/code-review, target/branch

#677 Fix after removal of postgres scripts and RHEL migration
  .ci/cico_do_docker_build_tag_push.sh
  config
  dev-scripts/deploy_custom_rh-che.sh
Labels: kind/bug, status/code-review, target/branch

#684 Fix variable unbound error that has broken the build
  config
Labels: kind/bug, status/code-review
