Repository redhat-developer/rh-che, pull requests merged in 2018-03, with the labels that each got.

#554 Changing resources names / labels to rhche for che6 deployment on prod / prod-preview osd
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: status/code-review, target/branch

#561 Updating ci files for che 6 deployment on osd
  .ci/cico_deploy.sh
  .ci/cico_do_docker_build_tag_push.sh
  config
Labels: status/code-review, target/branch

#562 Fixing build status to point to the correct 'rh-che6' job
  README.md
Labels: kind/bug, status/code-review, target/branch

#555 rh-che #541: Login to user project using oc CLI in workspace containers
  assembly/fabric8-stacks/src/main/resources/stacks.json
  plugins/fabric8-multi-tenant-manager/pom.xml
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8MultiTenantModule.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/OpenshiftUserTokenProvider.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisioner.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/TenantDataProvider.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/WorkspaceSubjectsRegistry.java
  plugins/fabric8-multi-tenant-manager/src/main/resources/installers/1.0.0/com.redhat.oc-login.json
  plugins/fabric8-multi-tenant-manager/src/main/resources/installers/1.0.0/com.redhat.oc-login.script.sh
  plugins/fabric8-multi-tenant-manager/src/test/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisionerTest.java
  plugins/fabric8-multi-tenant-manager/src/test/resources/logback-test.xml
  plugins/ls-bayesian-agent/pom.xml
  plugins/ls-bayesian-agent/src/main/java/com/redhat/bayesian/agent/BayesianTokenProvider.java
Labels: kind/enhancement, status/in-progress, target/branch

#571 Fix preview ur ls
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/bug, status/code-review, target/branch

#596 Add exec missing installer in stacks.json
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review, target/branch

#573 Created scripts for deploying che5 and che6 to openshift
  dev-scripts/deploy_custom_rh-che.sh
Labels: kind/enhancement, status/code-review, target/branch

#598 Adapt to changes of deploy files in upstream
  dev-scripts/deploy_custom_rh-che.sh
Labels: status/code-review, target/branch

#601 rh-che #597: fix Bayesian LS matching files by name instead of path
  plugins/che-plugin-bayesian-lang-server/src/main/java/org/eclipse/che/plugin/languageserver/bayesian/server/launcher/BayesianLanguageServerLauncher.java
Labels: kind/bug, status/code-review, target/branch

#602 Fixed according to @dfestal's notes
  dev-scripts/deploy_custom_rh-che.sh
Labels: kind/enhancement, status/code-review, target/branch

#604 Added possibility to switch branch of rh-che and modified docker imag…
  dev-scripts/deploy_custom_rh-che.sh
Labels: kind/enhancement, status/code-review, target/branch

#609 Fix warning in pom.xml
  assembly/fabric8-ide-gwt-app/pom.xml
Labels: kind/bug, status/code-review, target/branch

#600 Changes required to switch to `fabric8-auth` OIDC provider
  dev-scripts/deploy_custom_rh-che.sh
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisioner.java
  plugins/fabric8-multi-tenant-manager/src/test/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisionerTest.java
  pom.xml
Labels: kind/enhancement, status/code-review, target/branch

#605 Fix small shell error in CI script
  .ci/cico_do_build_che.sh
Labels: kind/bug, status/code-review, target/branch
