Repository redhat-developer/rh-che, pull requests merged in 2018-08, with the labels that each got.

#797 Dynamically assigned registry values - was static 'registry.devshift'
  .ci/cico_rhche_prcheck.sh
Labels: kind/bug, status/code-review

#799 End to end user registration flow with telemetry support.
  .ci/cico_rhche_prcheck.sh
  assembly/fabric8-ide-gwt-app/src/main/resources/org/eclipse/che/public/keycloak/OIDCKeycloak.js
  assembly/fabric8-ide-gwt-app/src/main/resources/org/eclipse/che/public/keycloak/RhCheKeycloak.js
  assembly/fabric8-ide-gwt-app/src/main/resources/org/eclipse/che/public/keycloak/provision.html
  dev-scripts/deploy_custom_rh-che.sh
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
  pom.xml
Labels: kind/task, status/code-review

#800 add central snapshots repo
  pom.xml
Labels: kind/enhancement, status/code-review

#777 Adding steps after Rh-Che build to prepare dependencies for pr-check
  .ci/cico_build_prcheck_dep.sh
  .ci/cico_do_docker_build_tag_push.sh
  README.md
  dockerfiles/pr-check/Dockerfile
  documentation/rh-che-prcheck/pr_check_general_squence_diagram.plantuml
  documentation/rh-che-prcheck/pr_check_general_squence_diagram.svg
Labels: kind/enhancement, status/code-review

#804 FIXUP: followup to #803 - fixing Dockerfile env variables
  dockerfiles/functional-tests/Dockerfile
  dockerfiles/functional-tests/google-chrome.repo
Labels: kind/bug, status/code-review

#787 Cleaning up stacks
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: status/code-review

#811 FT - simple suite
  functional-tests/src/test/resources/suites/simpleTestSuite.xml
Labels: status/code-review

#813 FT - workspace deletion fix
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/CheStarterWrapper.java
Labels: kind/bug, status/code-review

#818 Fix jenkins-env parting in dep build
  .ci/cico_build_prcheck_dep.sh
Labels: kind/bug, status/code-review

#819 Fixing docker dependency missing from slave
  .ci/cico_build_prcheck_dep.sh
Labels: kind/bug, status/code-review

#828 Hopefully the last fix -.- . Tested locally, everything seems to work fine.
  .ci/cico_build_prcheck_dep.sh
Labels: kind/bug, status/code-review

#837 Added formated date echo into the logs for debugging purposes
  .ci/cico_build_prcheck_dep.sh
Labels: kind/enhancement, status/code-review

#838 [WIP] rh-che Issue #826 - Update upstream Che to 6.10.0
  plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/test/java/com/redhat/che/plugin/analytics/wsagent/AnalyticsManagerTest.java
  plugins/che-plugin-analytics/che-plugin-analytics-wsmaster/src/main/java/com/redhat/che/plugin/analytics/wsmaster/ForwardActivityFilter.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8OpenShiftClientFactory.java
  pom.xml
Labels: kind/task, status/code-review
