Repository redhat-developer/rh-che, pull requests merged in 2018-06, with the labels that each got.

#688 rh-che #532 Using 'identity_id' as query parameter in oso proxy url
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/multicluster/MultiClusterOpenShiftProxy.java
Labels: kind/enhancement, status/code-review

#702 Bump to v6.5.3
  pom.xml
Labels: kind/bug, status/code-review

#697 Fix according to the changes Che 6.6
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/java/com/redhat/che/wsmaster/deploy/Fabric8WsMasterModule.java
  assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakModule.java
  openshift/minishift-addons/rhche/templates/rh-che.app.yaml
  openshift/rh-che.app.yaml
  plugins/che-plugin-analytics/che-plugin-analytics-wsagent/pom.xml
  plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/main/java/com/redhat/che/plugin/analytics/wsagent/UrlToEventFilter.java
  plugins/che-plugin-bayesian-lang-server/src/main/java/org/eclipse/che/plugin/languageserver/bayesian/BayesianLanguageServerModule.java
  plugins/che-plugin-bayesian-lang-server/src/main/java/org/eclipse/che/plugin/languageserver/bayesian/server/launcher/BayesianLanguageServerConfig.java
  plugins/che-plugin-bayesian-lang-server/src/main/java/org/eclipse/che/plugin/languageserver/bayesian/server/launcher/BayesianLanguageServerLauncher.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8OpenShiftClientFactory.java
  pom.xml
Labels: kind/bug, status/code-review

#705 Support private docker registries in OSIO
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8MultiTenantModule.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisioner.java
  plugins/fabric8-multi-tenant-manager/src/test/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisionerTest.java
  pom.xml
Labels: kind/enhancement, status/code-review

#710 Switch to the `6.6.2` bugfix release
  pom.xml
Labels: kind/bug, status/code-review

#711 Allow running rh-che in Minishift without other f8 services
  .ci/cico_deploy.sh
  .ci/cico_do_docker_build_tag_push.sh
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/rh-che.properties
  config
  openshift/minishift-addons/rhche-prerequisites/keycloak-configurator/.ceylon/config
  openshift/minishift-addons/rhche-prerequisites/keycloak-configurator/.gitignore
  openshift/minishift-addons/rhche-prerequisites/keycloak-configurator/Dockerfile
  openshift/minishift-addons/rhche-prerequisites/keycloak-configurator/source/keycloak_configurator/module.ceylon
  openshift/minishift-addons/rhche-prerequisites/keycloak-configurator/source/keycloak_configurator/run.ceylon
  openshift/minishift-addons/rhche-prerequisites/rhche-prerequisites.addon
  openshift/minishift-addons/rhche-prerequisites/rhche-prerequisites.addon.remove
  openshift/minishift-addons/rhche-prerequisites/templates/keycloak-template.yaml
  openshift/minishift-addons/rhche-prerequisites/templates/postgres-template.yaml
  openshift/minishift-addons/rhche/rhche.addon
  openshift/minishift-addons/rhche/rhche.addon.remove
  openshift/minishift-addons/rhche/templates/rh-che.app.yaml
  openshift/minishift-addons/rhche/templates/rh-che.config.yaml
  openshift/minishift-addons/rhche/templates/rh-che.secret.yaml
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/OpenshiftUserTokenProvider.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisioner.java
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/TenantDataProvider.java
  plugins/fabric8-multi-tenant-manager/src/main/resources/installers/1.0.0/com.redhat.oc-login.script.sh
  plugins/fabric8-multi-tenant-manager/src/test/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisionerTest.java
Labels: kind/docs, status/code-review

#720 Update upstream Che version to 6.7.0
  pom.xml
Labels: kind/enhancement, status/code-review

#722 Switching to 6.7.1 bug fix release (#10198)
  pom.xml
Labels: kind/enhancement, status/code-review
