Repository redhat-developer/rh-che, pull requests merged in 2018-12, with the labels that each got.

#1109 Add periodic job to README overview.
  README.md
Labels: kind/enhancement, status/code-review

#907 Adding scripts for rollout test
  .ci/cico_rollout_test.sh
  dockerfiles/functional-tests/docker-entrypoint.sh
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheTestWorkspaceImpl.java
  functional-tests/src/test/resources/suites/rolloutTest.xml
Labels: kind/enhancement, status/code-review

#1114 Define command type
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: status/code-review

#1105 Implement custom templates for running tests on different stacks
  .gitignore
  functional-tests/src/main/java/com/redhat/che/selenium/core/RhCheSeleniumSuiteModule.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/client/RhCheTestWorkspaceServiceClient.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheTestWorkspaceImpl.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheTestWorkspaceProvider.java
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/RhCheWorkspaceTemplate.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/TestTestClass.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/WorkspaceTest.java
  functional-tests/src/test/resources/suites/simpleTestSuite.xml
  functional-tests/src/test/resources/templates/workspace/che-starter/che-starter_nodejs.json
  functional-tests/src/test/resources/templates/workspace/che-starter/che-starter_vertx.json
  functional-tests/src/test/resources/templates/workspace/openshift/default.json
  functional-tests/src/test/resources/templates/workspace/openshift/nodejs_default.json
  functional-tests/src/test/resources/templates/workspace/openshift/vertx_default.json
Labels: kind/enhancement, status/code-review

#1113 Update README.md
  functional-tests/README.md
Labels: kind/enhancement, status/code-review

#1112 Update README for functional tests
  functional-tests/README.md
Labels: kind/enhancement, status/code-review

#1108 Implement test for running a workspace project
  functional-tests/src/test/java/com/redhat/che/functional/tests/BuildAndRunProjectTest.java
  functional-tests/src/test/resources/suites/simpleTestSuite.xml
Labels: kind/enhancement, status/code-review

#1120 Remove comment
  functional-tests/src/test/java/com/redhat/che/functional/tests/WorkspaceTest.java
Labels: status/code-review

#1128 rh-che #1111: Adding env var 'CHE_METRICS_ENABLED' for exposing metrics
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: kind/task, status/code-review

#1131 rh-che #1111: Exposing 8087 port for metrics
  openshift/rh-che.app.yaml
Labels: kind/task, status/code-review

#1133 rh-che #1116: Adding env var which allows to disable CORS
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: kind/task, status/code-review

#1137 Hotfix - remove keycloak token logic
  .ci/cico_rhche_prcheck.sh
  .ci/prepare_env_utils.sh
Labels: kind/bug, status/code-review

#1136 Fix compatibility test
  .ci/cico_rhche_compatibility_test.sh
Labels: kind/bug, status/code-review

#1086 Add new nodejs-postgres stack
  assembly/fabric8-stacks/src/main/resources/stacks.json
Labels: kind/enhancement, status/code-review

#1140 Remove verbose output when extracting analytics lsp agent.
  plugins/ls-bayesian-agent/src/main/resources/installers/1.0.0/com.redhat.bayesian.lsp.script.sh
Labels: status/code-review

#1141 Updating Readme.md
  README.md
Labels: kind/docs, status/code-review

#1132 Implement archiving artifacts for periodic tests (new suite)
  .ci/cico_rhche_compatibility_test.sh
  .ci/cico_rhche_prcheck.sh
  .ci/functional_tests_utils.sh
  functional-tests/devscripts/prepare_env.sh
  functional-tests/devscripts/run_tests.sh
  functional-tests/src/main/resources/configs/create-workspace-request.json
  functional-tests/src/test/resources/requests/workspace/osio/create-workspace-request.json
Labels: kind/enhancement, status/code-review

#1150 Fix archiving artifacts
  functional-tests/devscripts/prepare_env.sh
Labels: kind/bug, status/code-review

#1135 Abstract common behavior of test classes.
  functional-tests/pom.xml
  functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianAbstractTestClass.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianPackageJson.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianPomXml.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/BuildAndRunProjectTest.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/EETest.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/RhCheAbstractTestClass.java
Labels: status/code-review

#1153 Removing offline tokens
  dockerfiles/functional-tests/docker-entrypoint.sh
  functional-tests/devscripts/run_tests.sh
Labels: status/code-review
