Repository redhat-developer/rh-che, pull requests merged in 2019-02, with the labels that each got.

#1232 Enable PVC pre-create subpaths property by default.
  openshift/minishift-addons/rhche/templates/rh-che.config.yaml
  openshift/rh-che.config.yaml
Labels: kind/bug, status/code-review

#1219 Updating rh-che to the 6.18.0 upstream version
  pom.xml
Labels: status/code-review

#1243 Fixup for dev-cluster cleanup job.
  .ci/cico_cleanup_dev_cluster.sh
Labels: kind/bug, status/code-review

#1241 Ad traced annotation to RhChe infra provisioner
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisioner.java
Labels: status/code-review

#1246 Fix the Minishift RhChe addon
  openshift/minishift-addons/rhche-prerequisites/rhche-prerequisites.addon
  openshift/minishift-addons/rhche-prerequisites/templates/keycloak-template.yaml
Labels: kind/bug, status/code-review

#1245 Updating rh-che to the latest 6.18.1 upstream version
  pom.xml
Labels: kind/task, status/code-review

#1249 Fix the Exec permission bug in the RhChe minishift addon
  openshift/minishift-addons/rhche/rhche.addon
  openshift/minishift-addons/rhche/templates/che-workspace-service-account.yaml
  openshift/minishift-addons/rhche/templates/rh-che.config.yaml
Labels: kind/bug, status/code-review

#1252 Updating rh-che to the latest 6.18.2 upstream version
  pom.xml
Labels: status/code-review

#1251 rh-che #1216 Removing 'CHE_WORKSPACE_PLUGIN__BROKER_INIT_IMAGE' entry from cm
  openshift/rh-che.config.yaml
Labels: kind/task, status/code-review

#1250 Ensure addon serviceaccount is created in same namespace
  openshift/minishift-addons/rhche/rhche.addon
Labels: status/code-review

#1257 WIP - Workaround for importing project
  functional-tests/src/test/java/com/redhat/che/functional/tests/RhCheAbstractTestClass.java
  functional-tests/src/test/resources/suites/prcheck.xml
Labels: status/code-review

#1222 Make tests on prod green
  functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianAbstractTestClass.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianPomXml.java
Labels: status/code-review

#1258 Updating README info about PR check.
  README.md
  functional-tests/src/test/resources/suites/prcheck.xml
Labels: status/code-review

#1218 Fixing cleanup job.
  .ci/cico_cleanup_dev_cluster.sh
  .ci/cico_rollout_test.sh
  .ci/functional_tests_utils.sh
Labels: kind/bug, status/code-review
