Repository redhat-developer/rh-che, pull requests merged in 2019-07, with the labels that each got.

#1464 Gather events from tests
  .ci/functional_tests_utils.sh
  functional-tests/devscripts/run_tests.sh
Labels: status/code-review

#1469 Fixed docker image build issues
  dockerfiles/pr-check/Dockerfile
Labels: kind/bug, status/code-review

#1472 Enabled selenium tests to use old stack-based approach
  functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianAbstractTestClass.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianPackageJson.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianPomXml.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/Che7DialogAbout.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/RhCheAbstractTestClass.java
Labels: kind/enhancement, status/code-review

#1465 Add script to check for upstream dashboard changes when updating version
  dev-scripts/check-upstream-dashboard.sh
Labels: kind/enhancement, status/code-review

#1452 Run e2e test as a flaky
  .ci/cico_build_func_dep.sh
  dockerfiles/e2e-saas/Dockerfile
  dockerfiles/e2e-saas/docker-entrypoint.sh
  dockerfiles/e2e-saas/google-chrome.repo
  e2e-saas/mocha.opts
  e2e-saas/tests/HappyPath.spec.ts
  functional-tests/devscripts/run_tests.sh
Labels: status/code-review

#1505 Fix ephemeral mode default when creating workspace
  assembly/fabric8-ide-dashboard-war/src/app/workspaces/create-workspace/create-workspace.controller.ts
Labels: kind/bug
