Repository redhat-developer/rh-che, pull requests merged in 2019-01, with the labels that each got.

#1146 Updating rh-che to the latest 6.16.0 upstream version
  assembly/assembly-wsmaster-war/pom.xml
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
  plugins/che-plugin-bayesian-lang-server/pom.xml
  plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisioner.java
  plugins/fabric8-multi-tenant-manager/src/test/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisionerTest.java
  pom.xml
Labels: status/code-review

#1156 Refactor scripts
  .ci/cico_cleanup_dev_cluster.sh
  .ci/cico_rhche_compatibility_test.sh
  .ci/cico_rhche_prcheck.sh
  .ci/cico_rollout_test.sh
  .ci/functional_tests_utils.sh
Labels: status/code-review

#1183 Fix rollout
  .ci/cico_rollout_test.sh
Labels: kind/bug, status/code-review

#1187 Fix end-to-end test
  functional-tests/src/test/java/com/redhat/che/functional/tests/EETest.java
Labels: kind/bug, status/code-review

#1186 Clear warnings from tests, simplify test output
  functional-tests/devscripts/prepare_env.sh
  functional-tests/devscripts/run_tests.sh
  functional-tests/src/main/java/com/redhat/che/selenium/core/workspace/CheStarterWrapper.java
  functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianAbstractTestClass.java
Labels: kind/enhancement, status/code-review

#1208 Fix setting of protocol in docker entrypoint.
  dockerfiles/functional-tests/docker-entrypoint.sh
Labels: kind/bug, status/code-review

#1212 Update version of init broker to 0.7.1
  openshift/rh-che.config.yaml
Labels: kind/bug, status/code-review

#1162 Enabled job that stops workspaces without pods
  openshift/rh-che.config.yaml
Labels: kind/enhancement, status/code-review

#1200 Disable Ipv6 lookup for che master, workspace agent and for java ops
  openshift/rh-che.config.yaml
Labels: kind/enhancement, status/code-review

#1192 Pre-fetching of the default editor CDN resources
  assembly/assembly-wsmaster-war/pom.xml
  assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/rh-che.properties
  assembly/fabric8-ide-dashboard-war/pom.xml
  assembly/fabric8-ide-dashboard-war/src/components/ide-fetcher/che-ide-fetcher.service.ts
  dev-scripts/deploy_custom_rh-che.sh
  dockerfiles/che-fabric8/Dockerfile
  openshift/rh-che.config.yaml
  plugins/fabric8-cdn-support/pom.xml
  plugins/fabric8-cdn-support/src/main/java/com/redhat/che/cdn/CdnSupportService.java
  plugins/fabric8-cdn-support/src/main/java/com/redhat/che/cdn/CdnSupportWsMasterModule.java
  plugins/fabric8-cdn-support/src/test/java/com/redhat/che/cdn/CdnSupportServiceTest.java
  plugins/fabric8-cdn-support/src/test/resources/che-editor-plugin.tar.gz
  plugins/pom.xml
  pom.xml
Labels: status/code-review

#1214 Updating to the latest 6.17.1 upstream version
  pom.xml
Labels: status/code-review

#1205 Switching prcheck to new tests.
  .ci/cico_build_deploy_test_rhche.sh
  .ci/cico_rhche_prcheck.sh
  .ci/functional_tests_utils.sh
  dockerfiles/functional-tests/docker-entrypoint.sh
  functional-tests/README.md
  functional-tests/devscripts/run_tests.sh
  functional-tests/src/test/resources/suites/prcheck.xml
Labels: status/code-review

#1220 rh-che-979: Adding dev docs for 'che-plugin-registry' updates
  dev-guide.adoc
  documentation/images/plugins.png
Labels: kind/enhancement, status/code-review

#1223 #979 Adding docs for updating template / cm for deployment on different infrastructure
  dev-guide.adoc
Labels: kind/enhancement, status/code-review
