Repository redhat-developer/rh-che, pull requests merged in 2019-03, with the labels that each got.

#1253 Updating rh-che to the latest 7.0.0-beta-1.0 upstream version
  pom.xml
Labels: kind/task, status/code-review

#1285 Add documentation about monitoring rhche in production
  dev-guide.adoc
  documentation/monitoring/images/graphana-usage.gif
  documentation/monitoring/images/jaeger-example.png
  documentation/monitoring/monitoring.adoc
Labels: kind/docs

#1322 Added dockerfile for load-tests image
  dockerfiles/load-tests/Dockerfile
  dockerfiles/load-tests/entrypoint.sh
  load-tests/README.md
Labels: kind/enhancement, status/code-review

#1335 Adding websocket env var option for docker run parameters
  dockerfiles/load-tests/entrypoint.sh
  load-tests/README.md
  load-tests/real-life.py
Labels: kind/enhancement, status/code-review

#1323 Change rhche JSONRPC queue settings
  openshift/rh-che.app.yaml
  openshift/rh-che.config.yaml
Labels: kind/enhancement, severity/P1, status/code-review
