Repository redhat-developer/rh-che, pull requests merged in 2019-09, with the labels that each got.

#1601 Fixing CDN tests due to changes in the che-plugin-registry (explicit reference to docker.io registry in '7.1.0' release)
  plugins/fabric8-cdn-support/src/test/java/com/redhat/che/cdn/HttpYamlDownloaderTest.java
Labels: kind/bug, status/code-review

#1584 [E2E] Update info in README.md
  e2e-saas/README.md
Labels: status/code-review

#1606 [E2E] Removing bail as removing of workspace not working.
  e2e-saas/mocha.opts
Labels: status/code-review

#1608 [E2E] Fix LS test.
  e2e-saas/tests/HappyPath.spec.ts
Labels: kind/task, status/code-review

#1616 [E2E] Parameterize docker run command.
  dockerfiles/e2e-saas/Dockerfile
  dockerfiles/e2e-saas/docker-entrypoint.sh
  e2e-saas/README.md
  e2e-saas/mocha-java-maven.opts
  e2e-saas/package.json
  e2e-saas/tests/JavaMaven.spec.ts
Labels: kind/task, status/code-review

#1623 [E2E] Add Vert.x test to production
  functional-tests/devscripts/run_tests.sh
Labels: status/code-review
